In [1]:
import numpy as np

def eliminacion_gaussiana(matriz_aumentada):
    n = len(matriz_aumentada)

    for i in range(n):
        print(f"\nPaso {i + 1}:")
        print(matriz_aumentada)

        # Buscar el pivote no nulo en la columna actual
        pivote_no_nulo = False
        for k in range(i, n):
            if matriz_aumentada[k][i] != 0:
                pivote_no_nulo = True
                # Intercambiar filas si es necesario
                if k != i:
                    matriz_aumentada[[i, k]] = matriz_aumentada[[k, i]]
                break

        if not pivote_no_nulo:
            raise ValueError("El sistema no tiene solución única.")

        # Hacer la fila i el pivote
        pivot_row = matriz_aumentada[i]
        pivot_element = pivot_row[i]

        # Normalizar la fila del pivote
        matriz_aumentada[i] = pivot_row / pivot_element

        print(f"Normalizando fila {i + 1}:")
        print(matriz_aumentada)

        # Eliminar otras filas
        for j in range(n):
            if i != j:
                factor = matriz_aumentada[j][i]
                matriz_aumentada[j] -= factor * matriz_aumentada[i]

                print(f"Eliminando fila {i + 1} de la fila {j + 1}:")
                print(matriz_aumentada)

    # Verificar si hay alguna fila sin solución
    for fila in matriz_aumentada:
        if np.all(fila[:-1] == 0) and fila[-1] != 0:
            raise ValueError("El sistema no tiene solución única.")

    # Extraer los resultados
    soluciones = matriz_aumentada[:, -1]

    return soluciones

def ingreso_variables(n):
    while True:
        try:
            variables = input("Ingrese los nombres de las variables separados por espacio: ").split()

            # Verificar si el número de variables es igual al número de ecuaciones
            if len(variables) != n:
                raise ValueError("El número de variables no coincide con el número de ecuaciones. Intente nuevamente.")

            # Verificar si todas las variables son diferentes
            if len(set(variables)) != n:
                raise ValueError("Ingrese nombres de variables diferentes. Intente nuevamente.")
            
            return variables
        except ValueError as e:
            print(f"Error: {e}")

def ingreso_coeficientes(variables):
    while True:
        try:
            print(f"Ingrese los coeficientes para cada ecuación  {', '.join(variables)} ejemplo 2 0 4 representa 2x+0y=5:")
            sistema = []
            for _ in range(len(variables)):
                try:
                    coeficientes = list(map(float, input().split()))

                    # Verificar si el número de coeficientes es correcto
                    if len(coeficientes) != len(variables) + 1:
                        raise ValueError(f"Ingrese exactamente {len(variables) + 1} coeficientes por ecuación.")

                    sistema.append(coeficientes)
                except ValueError:
                    raise ValueError("Formato incorrecto de coeficientes. Ingrese números separados por espacios.")

            matriz_aumentada = np.array(sistema)
            return matriz_aumentada
        except ValueError as e:
            print(f"Error: {e}. Intente nuevamente.")

def main():
    try:
        n = int(input("Ingrese el número de ecuaciones: "))
        variables = ingreso_variables(n)
        matriz_aumentada = ingreso_coeficientes(variables)

        soluciones = eliminacion_gaussiana(matriz_aumentada)

        print("\nSoluciones:")
        for i, solucion in enumerate(soluciones):
            print(f"{variables[i]} = {solucion:.2f}")
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()

Ingrese el número de ecuaciones: 2
Ingrese los nombres de las variables separados por espacio: X Y
Ingrese los coeficientes para cada ecuación  X, Y:
2 3 5
4
Error: Formato incorrecto de coeficientes. Ingrese números separados por espacios.. Intente nuevamente.
Ingrese los coeficientes para cada ecuación  X, Y:
2 3 5
5 0 9

Paso 1:
[[2. 3. 5.]
 [5. 0. 9.]]
Normalizando fila 1:
[[1.  1.5 2.5]
 [5.  0.  9. ]]
Eliminando fila 1 de la fila 2:
[[ 1.   1.5  2.5]
 [ 0.  -7.5 -3.5]]

Paso 2:
[[ 1.   1.5  2.5]
 [ 0.  -7.5 -3.5]]
Normalizando fila 2:
[[ 1.          1.5         2.5       ]
 [-0.          1.          0.46666667]]
Eliminando fila 2 de la fila 1:
[[ 1.          0.          1.8       ]
 [-0.          1.          0.46666667]]

Soluciones:
X = 1.80
Y = 0.47
